# Generated by Django 2.1.7 on 2019-02-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_auto_20190213_0027'),
        ('core', '0002_pedido_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(to='itens.Produto'),
        ),
    ]
