# Generated by Django 2.1.7 on 2019-02-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_auto_20190213_0027'),
        ('core', '0003_auto_20190213_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itens.Produto'),
            preserve_default=False,
        ),
    ]
