# Generated by Django 2.1.7 on 2019-02-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_auto_20190213_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço'),
        ),
    ]
